version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: proj1-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: proj1-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - ./.env

  mongodb:
    image: mongo:7.0.2
    container_name: proj1-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    env_file:
      - ./.env

  producer:
    build: 
      context: ./producer
      dockerfile: Dockerfile
    container_name: proj1-producer
    image: proj1/producer
    env_file:
      - ./.env

  consumer:
    build: 
      context: ./consumer
      dockerfile: Dockerfile
    container_name: proj1-consumer
    image: proj1/consumer
    depends_on:
      - mongodb
      - kafka
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: proj1-redis
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
    command: redis-server --save 20 1 --loglevel warning
    env_file:
      - ./.env

  warmer:
    build: 
      context: ./warmer
      dockerfile: Dockerfile
    container_name: proj1-warmer
    image: proj1/warmer
    env_file:
      - ./.env

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: proj1-web
    ports:
      - 5050:5000
    image: proj1/web
    env_file:
      - ./.env
